# config file for defis

site_id: defis

datagouvfr:
  # data.gouv.fr base URL
  base_url: https://www.data.gouv.fr
  # oauth settings
  oauth_client_id: 670924ba96082fcc26ee3898
  tabular_api_url:

robots:
  disallow:
  sitemap:
  meta: 'noindex, nofollow'

# UI customizations
website:
  title: 'defis.data.gouv.fr'
  rf_title: 'RÉPUBLIQUE<br>
    FRANÇAISE'
  service_logo: '/logos/defis-logo.svg'
  badge:
    display: true
    text: 'BETA'
    style: 'blue-cumulus'
  # leave empty if not pertinent
  homepage:
    title: 'Apprendre avec l’open data'
    subtitle: 'Utiliser les données publiques pour répondre à des enjeux sociaux et environnementaux.'
    sections:
      - title:
        content: Les données ouvertes (open data) sont des données brutes téléchargeables en accès libre et gratuit qui peuvent être utilisées par toutes et tous. Elles permettent de créer des analyses, des services ou des produits sur une diversité de sujets (santé, emploi, urbanisme, éducation, mobilités, etc.).
      - title: Des ressources pédagogiques
        content: L’équipe de data.gouv.fr structure des ressources pédagogiques qui vous fournissent les éléments essentiels pour apprendre à exploiter des données ouvertes rapidement. Il s’agit d’une articulation de ressources externes et de contenus produits par data.gouv.fr.
        sub_section_datasets:
        sub_section_tiles:
          title:
          class: 'fr-col-md-4'
          tiles:
            - id: 'find'
              name: 'Trouver des données'
              description: 'Où rechercher des jeux de données'
              url: 'https://guides.data.gouv.fr/reutiliser-des-donnees/guide-traitement-et-analyse-de-donnees/trouver-des-donnees'
            - id: 'evaluate'
              name: 'Evaluer la qualité des données'
              description: "Comment s'informer sur un jeu de données"
              url: 'https://guides.data.gouv.fr/reutiliser-des-donnees/guide-traitement-et-analyse-de-donnees/prendre-connaissance-et-evaluer-la-qualite-de-donnees'
            - id: 'get'
              name: 'Récupérer des données'
              description: 'Comment télécharger des données ou utiliser une API'
              url: 'https://guides.data.gouv.fr/reutiliser-des-donnees/guide-traitement-et-analyse-de-donnees/recuperer-des-donnees'
            - id: 'manipulate'
              name: 'Manipuler des données'
              description: 'Comment ouvrir, filtrer, nettoyer ou croiser des données'
              url: 'https://guides.data.gouv.fr/reutiliser-des-donnees/guide-traitement-et-analyse-de-donnees/manipuler-des-donnees'
            - id: 'analyze'
              name: 'Analyser des données'
              description: "Comment utiliser un tableur, python ou R pour l'analyse"
              url: 'https://guides.data.gouv.fr/reutiliser-des-donnees/guide-traitement-et-analyse-de-donnees/analyser-des-donnees'
            - id: 'show'
              name: 'Visualiser des données'
              description: 'Comment créer des visualisations de données'
              url: 'https://guides.data.gouv.fr/reutiliser-des-donnees/guide-traitement-et-analyse-de-donnees/visualiser-des-donnees'

      - title: Des défis open data
        content: >
          La communauté open data et l’équipe de data.gouv.fr vous proposent de mettre à contribution et de développer vos compétences en réalisant des projets utiles à partir de données ouvertes.


          Les défis proposés s’adressent notamment à toutes celles et ceux qui souhaitent s’exercer ou apprendre à exploiter des données en travaillant sur des projets concrets.
      - title:
        content:
        sub_section_datasets:
        sub_section_cards:
          title:
          cards:
            - id: '68234dc8f8f4d7549998f0ad'
              name: 'Santé et territoires'
              description: 'Comment aider les acteurs locaux à réaliser un diagnostic de santé publique ? Défi porté par la Fondation Roche'
              url: '/defis/sante-et-territoires'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/refs/heads/main/Visuel-ODU-Sante.jpg'
            - id: '67f5438a3b2d79d922863e03'
              name: 'Diversité et inclusion en entreprise'
              description: 'Quelle politique sur l’inclusion et la diversité au sein d’EDF SA ? Défi porté par EDF'
              url: '/defis/diversite-et-inclusion-en-entreprise'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/refs/heads/main/Saison3_EDF2.jpg'
            - id: '6704d7a9120c998a2085f8bc'
              name: 'Revitalisation des petites villes'
              description: 'Comment représenter les spécificités d’une petite ville de demain ? Défi porté par la Banque des Territoires'
              url: '/defis/revitalisation-des-petites-villes'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/refs/heads/main/Saison3_PVD2.jpg'
            - id: '65b76f15d7874915c8e41298'
              name: 'Impact Diagnostics de Performance Energétique'
              description: 'Quel impact de la classe DPE sur les consommations énergétiques ? Défi porté par Enedis'
              url: '/defis/diagnostics-de-performance-energetique'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/refs/heads/main/Saison3_Enedis.jpg'
            - id: '6710e8d60f12d58334949614'
              name: 'Les Françaises et Français face à l’information'
              description: 'Comment qualifier l’offre et l’évolution des modes de "consommation" de l’information ?'
              url: '/defis/les-francaises-et-francais-face-a-linformation'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/refs/heads/main/Saison3_Information2.jpg'
            - id: '65b10aa72d0c187ecf296930'
              name: 'Offre culturelle'
              description: "Comment valoriser l'offre culturelle et favoriser l'accès à la culture ?"
              url: '/defis/offre-culturelle'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/refs/heads/main/Saison3_Culture.jpg'
            - id: '65b22219ffcf892bd066df76'
              name: 'Elections'
              description: 'Quels liens entre vote et caractéristiques socio-démographiques ?'
              url: '/defis/elections'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/refs/heads/main/Saison3_Elections.jpg'
            - id: '65a923a083cf5f728c9934b3'
              name: 'Véhicules électriques'
              description: 'La répartition des infrastructures de recharge est-elle adaptée ?'
              url: '/defis/vehicules-electriques'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/refs/heads/main/Saison3_Vehicules-electriques.jpg'
            - id: '65b10beae24f409e31c547a5'
              name: 'Changement climatique'
              description: 'Quelle évolution du climat en France depuis le début du XXe siècle ?'
              url: '/defis/changement-climatique'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/odu_climat3.png'
            - id: '65b76b8536f029909a82ca1c'
              name: 'Commerces de centre-ville'
              description: 'Quelle est la structure du tissu commercial ?'
              url: '/defis/commerces-de-centre-ville'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/odu_commerces3.png'
            - id: '65a92352ddd3d98e460e83f3'
              name: 'Infrastructures cyclables'
              description: 'Quels liens entre accidentologie à vélo et infrastructures cyclables ?'
              url: '/defis/infrastructures-cyclables'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/odu_velo3.png'
            - id: '65a92372953d21f206abb110'
              name: 'Energie en France'
              description: 'Quelles tensions énergétiques passées et futures en France ?'
              url: '/defis/energie-en-france'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/energie3_odu.png'
            - id: '65a9237ed493a309fc872e4a'
              name: 'Carte scolaire'
              description: 'Comment permettre de savoir dans quel établissement inscrire un enfant ?'
              url: '/defis/carte-scolaire'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/odu_ecole4.png'
            - id: '65a9238c202514467c0163d2'
              name: 'Plan France Relance'
              description: "Quels impacts des aides distribués sur l'économie et la transition écologique ?"
              url: '/defis/plan-france-relance'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/odu_francerelance3.png'
            - id: '66a0fdf41a40f23f40025444'
              name: 'Accès au sport'
              description: "Sport pour tous : Évaluer et améliorer l'égalité d'accès aux activités sportives en France"
              url: 'defis/acces-au-sport'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/defi-acces-au-sport.jpg'
            - id: '6639df879e70e0b00e5aeef1'
              name: 'Accès et exploitation des données météorologiques'
              description: 'Comment faciliter la manipulation des données météorologiques ?'
              url: 'defis/acces-aux-donnees-meteos'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/refs/heads/main/acces-meteo.jpg'
            - id: '6639e67fa95c6e4f1da70e39'
              name: 'Décision agricole'
              description: 'Comment informer la prise de décision à partir des données météorologiques ?'
              url: 'defis/decision-agricole'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/refs/heads/main/decision-agricole.jpg'
            - id: '6639e311f4a75be320cfa517'
              name: 'Énergies renouvelables'
              description: "Comment prévoir les variations de production d'énergies renouvelables ?"
              url: 'defis/energies-renouvelables'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/refs/heads/main/energies-renouvelables.jpg'
            - id: '6639ea1a5fde712a09fa0c67'
              name: 'Îlots de chaleur urbain'
              description: "Comment identifier les zones sujettes à l'effet d'îlot de chaleur urbain ?"
              url: 'defis/ilots-de-chaleur-urbain'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/refs/heads/main/ilot-de-chaleur.jpg'
            - id: '66a0ffa8d8f03afc1d474a53'
              name: 'JOP2024 et offre culturelle'
              description: "Jeux Olympiques et Paralympiques : Enrichissez l'expérience et mettez en valeur l'offre culturelle"
              url: 'defis/jop2024-et-offre-culturelle'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/defi-jo-offre-culturelle.jpg'

        sub_section_tiles:
        sub_section_buttons:
      - title:
        content: >-
          ### L'Open Data University

          Ces défis ont été développés dans le cadre de [l’Open Data University](https://www.opendatauniversity.org/), un programme d’enseignement à la réutilisation des données publiques porté par [l'association Latitudes](https://www.latitudes.cc/) et dont data.gouv.fr est partenaire.


          Enseignantes, enseignants et responsables pédagogiques des établissements d'enseignement supérieur, [n'hésitez pas à vous inscrire pour intégrer le dispositif](https://airtable.com/appJY09hYLFOYjGdc/shr7WX6sMS1ciiyMv) !


          [En savoir plus sur l’Open Data University.](/opendatauniversity)
    meta_description:
  header_button:
    display: false
    label: 'Donnez votre avis'
    link: https://tally.so/r/wQ7y47
  header_search:
    display: false
  search_bar:
    display: false
    placeholder: 'Rechercher un jeu de données'
  secondary_search:
    display: false
    name:
    link:
  menu:
    - text: Défis
      to: /defis
    - text: Open Data University
      to: /opendatauniversity
    - text: Guides
      to: https://guides.data.gouv.fr/
  router:
    disable:
      - organizations_routes
    static_pages:
      - title: 'Open Data University'
        id: 'opendatauniversity'
        route: '/opendatauniversity'
        url: '/defis/pages/opendatauniversity.md'
      - title: 'Accessibilité'
        id: 'accessibility'
        route: '/accessibility'
        url: '/defis/pages/accessibility.md'
  show_quality_component: true
  show_dataset_metadata_panel: false
  oauth_option: true
  footer_phrase: 'Ce site présente des exemples de défis de réutilisations de données publiques sélectionnés par l’équipe data.gouv.fr en collaboration avec les producteurs de données.'
  footer_external_links:
    - label: 'data.gouv.fr'
      href: 'https://www.data.gouv.fr'
    - label: 'Association Latitudes'
      href: 'https://www.latitudes.cc/'
  footer_mandatory_links:
    - label: 'Licences'
      href: 'https://www.data.gouv.fr/fr/pages/legal/licences/'
    - label: "Conditions générales d'utilisation"
      href: 'https://www.data.gouv.fr/fr/terms/'
    - label: 'Politique de confidentialité'
      href: 'https://www.data.gouv.fr/fr/suivi/'
    - label: 'Accessibilité : non conforme'
      to: '/accessibility'
  logo_operator:
  notice:
    display: false
    content: Notice avec un [lien beta](/beta) et du _style_
    closeable: false
  # debounce high enough for accessibility (screen readers will announce results)
  default_debounce_wait: 600
  # display settings
  pagination_sizes:
    organizations_list: 9
    topics_list: 20
    files_list: 6
  home_banner_colors:
    - '#DDE6FF'
    - '#A1C7ED'
    - '#6AB9B5'
  env: 'prod'
  matomo:
    host:
    siteId:
  datasets:
    add_to_topic:
    # similar to QUALITY_METADATA_BACKEND_IGNORE on data.gouv.fr
    harvest_backends_quality_warning: []
    show_extended_information_panel: false
  topics:
    can_add_topics:
      everyone: false
      authorized_users:
        - 5fda299e56f984a4b126afe1 # thanh-ha
        - 5e6f426e634f417810ab794b # geoffrey
        - 65e8b5082f2504e916c8f6da # ecospheres

pages:
  # DEFIS
  defis:
    list_all: true
    universe_query:
      tag: defisdatagouvfr
    tag_prefix: defisdatagouvfr
    title: Défis
    breadcrumb_title: Défis
    labels:
      singular: défi
      plural: défis
      extended: défi
    search:
      input: Chercher un défi
    banner:
    resources_tabs:
      discussions:
        display: false
        create: false
      datasets:
        display: true
      reuses:
        display: true
    editable: true
    filters:
      - name: Saison
        default_option: Toutes les saisons
        id: saison
        type: select
        color: green-emeraude
        use_tag_prefix: true
        form:
          required: true
        values:
          - id: saison-1
            name: Saison 1
          - id: saison-2
            name: Saison 2
          - id: saison-3
            name: Saison 3
  # DATASETS
  datasets:
    list_all: false
    universe_query:
    tag_prefix:
    title:
    breadcrumb_title: Données
    labels:
      singular: jeu de données
      plural: jeux de données
      extended: jeu de données
    search:
      input:
    banner:
    resources_tabs:
      discussions:
        display: false
        create: false
      datasets:
        display: true
      reuses:
        display: true
    filters: []

# list of organisations' ids that should be handled by the portal
# to find an id go to https://www.data.gouv.fr/fr/organizations/ministere-de-la-transition-ecologique/
# then Informations > ID at the bottom of the page
organizations:
