# config file for accessibilite.data.gouv.fr

site_id: accessibilite

datagouvfr:
  # data.gouv.fr base URL
  base_url: https://demo.data.gouv.fr
  # oauth settings
  oauth_client_id: 682c45ba772ed4a274715025
  tabular_api_url: https://tabular-api.preprod.data.gouv.fr

# UI customizations
website:
  title: "Point d'accès unique aux données d'accessibilité"
  seo:
    canonical_url: https://accessibilite.data.gouv.fr
    meta:
      keywords:
      description:
      robots: 'noindex, nofollow'
    robots_txt:
      disallow:
        - /admin
    sitemap_xml:
      topics_pages:
        - themes
      datasets_pages: []
      dataservices_pages: []
  formatted_title: '<b>accessibilite.data.gouv.fr</b>'
  rf_title: 'RÉPUBLIQUE<br>
    FRANÇAISE'
  # leave empty if not pertinent
  homepage:
    title:
    subtitle:
    sections:
      - title:
        content:
        sub_section_datasets:
        sub_section_cards:
        sub_section_tiles:
        sub_section_buttons:
    meta_description: accessibilite.data.gouv.fr référence et centralise les données relatives à l'accesssibilité.
  footer:
    logo:
      src: /static/logos/accessibilite-logo.svg
      width: 120px
      height: 49px
    phrase: "Ce site est une déclinaison thématique de data.gouv.fr pour les données relatives à l'accessibilité."
    external_links:
      - label: 'data.gouv.fr'
        href: 'https://www.data.gouv.fr'
    mandatory_links:
      - label: 'Licences'
        to: 'https://www.data.gouv.fr/fr/pages/legal/licences/'
      - label: "Conditions générales d'utilisation"
        to: 'https://www.data.gouv.fr/fr/terms/'
      - label: 'Politique de confidentialité'
        to: 'https://www.data.gouv.fr/fr/suivi/'
      - label: 'Accessibilité : non conforme'
        to: '/accessibility'
  header:
    admin_shortcut: false
    logo:
      src: /static/logos/accessibilite-logo.svg
    title_image:
    description: accessibilite.data.gouv.fr
    beta: true
    button:
      display: false
      label: 'Donnez votre avis'
      link:
    search:
      display: false
      placeholder: Rechercher...
  search_bar:
    display: false
    placeholder: Rechercher un jeu de données
  secondary_search:
    display: false
    name:
    link:
  menu:
    - text: Accueil
      to: /
    - text: Toutes les données
      to: /datasets
    - text: Données par thème
      to: /themes
    - text: Mots expliqués
      to: /glossaire
    - text: Pourquoi ce site ?
      to: /about
  router:
    static_pages:
      - title: 'Mots expliqués'
        id: 'glossaire'
        route: '/glossaire'
        summary:
          display: true
          inline: true
          title: 'Accès par lettre pour trouver un mot expliqué'
        url: '/static/accessibilite/pages/glossaire.md'
      - title: 'Pourquoi ce site ?'
        id: 'about'
        route: '/about'
        url: '/static/accessibilite/pages/about.md'
        summary:
          display: true
  sitemap:
    - name: Accueil
      path: /
    - name: Toutes les données
      path: /datasets
    - name: Données par thème
      path: /themes
    - name: Pourquoi ce site ?
      path: /about
  show_quality_component: true
  oauth_option: true
  notice:
    display: true
    content: ⚠️ Vous naviguez sur une version de développement d'accessibilite.data.gouv.fr ⚠️
    closeable: false
  # debounce high enough for accessibility (screen readers will announce results)
  default_debounce_wait: 600
  # display settings
  pagination_sizes:
    organizations_list: 9
    topics_drafts_list: 9
    files_list: 6
  home_banner_colors:
    - '#FFFFFF'
    - '#FFFFFF'
    - '#FFFFFF'
  contact_email:
  matomo:
    host: 'https://stats.data.gouv.fr'
    siteId:
  datasets:
    open_in_qgis: false
    add_to_topic:
      enable: true
      page: themes
      dataset_editorialization: true
    # similar to QUALITY_METADATA_BACKEND_IGNORE on data.gouv.fr
    harvest_backends_quality_warning: []
    show_extended_information_panel: false
  topics:
    can_add_topics:
      everyone: false
      authorized_users: ['69e0effc2ca128bf0bf1fea9', '69e0f509cf1ecaf5f33f2977']

# cf configs/ecospheres/config.yaml for pages config format details
pages:
  # DATASETS
  datasets:
    object_type: datasets
    list_all: true
    universe_query:
      topic: 69f3767828440f63bfc33a1d
    filter_prefix:
    title: Jeux de données
    breadcrumb_title: Données
    labels:
      singular: jeu de données
      plural: jeux de données
      extended: jeu de données
    search:
      input: Rechercher un jeu de données
      placeholder: null
    banner:
    resources_tabs:
      discussions:
        display: true
        create: true
      datasets:
        display: true
      reuses:
        display: true
    editable: true
    filters: []
  # THÈMES (BOUQUETS)
  themes:
    object_type: topics
    list_all: true
    universe_query:
      tag: accessibilite-univers
    filter_prefix: accessibilite-univers
    title: Données par thèmes
    breadcrumb_title: Thèmes
    labels:
      singular: thème
      plural: thèmes
      extended: thème
      feminine: false
    search:
      input: Filtrer les thèmes
      placeholder: null
    banner:
    resources_tabs:
      discussions:
        display: true
        create: true
      datasets:
        display: true
      reuses:
        display: true
    editable: true
    filters:
      - name: Thématique
        default_option: Toutes les thématiques
        id: theme
        type: select
        color: green-emeraude
        use_filter_prefix: true
        form:
          required: true
        values:
          - id: accessibilite-tourisme
            name: Tourisme
          - id: accessibilite-quotidienne
            name: Vie quotidienne
          - id: accessibilite-loisirs
            name: Loisirs
          - id: accessibilite-communication
            name: Communication
          - id: accessibilite-enseignement
            name: Enseignement
          - id: accessibilite-sante
            name: Santé
          - id: accessibilite-logement
            name: Logement
          - id: accessibilite-autonomie
            name: Autonomie
          - id: accessibilite-emploi
            name: Emploi
      - name: Couverture territoriale
        default_option:
        id: geozone
        type: geozone

# list of organisations' ids that should be handled by the portal
# to find an id go to https://www.data.gouv.fr/fr/organizations/ministere-de-la-transition-ecologique/
# then Informations > ID at the bottom of the page
organizations:

accessibilite:
  homepage:
    sponsors:
      - name: Délégation interministérielle à l'accessibilité
        logo: logo-DIA
      - name: La fabrique de la donnée territoriale
        logo: logo-fabrique-territoriale
      - name: Institut national de l'information géographique et forestière
        logo: logo-IGN
      - name: Caisse nationale pour la solidarité à l’autonomie
        logo: logo-cnsa
      - name: beta.gouv
        logo: logo-beta.gouv
      - name: Commissariat général au développement durable
        logo: logo-ecolab
      - name: datagouv
        logo: logo-datagouv
      - name: Direction interministérielle du numérique
        logo: logo-DINUM
      - name: Délégation ministérielle à l'accessibilité
        logo: logo-DMA
    partners:
      - name: Association des maires ruraux de France
        logo: logo-amrf
      - name: collectif handicap visuel
        logo: logo-collectif-handicap-visuel
      - name: Départements de France
        logo: logo-departements
      - name: France urbaine
        logo: logo-france-urbaine
      - name: Régions de France
        logo: logo-regions-france
      - name: Union des associations nationales pour l'inclusion des malentendants et des sourds
        logo: logo-unanimes
      - name: Union nationale des associations de parents d’enfants déficients auditifs
        logo: logo-unapeda
      - name: Union nationale des associations de parents d'enfants inadaptés
        logo: logo-unapei
