# config file for accessibilite.data.gouv.fr

# used as extras key
site_id: accessibilite

datagouvfr:
  # data.gouv.fr base URL (use www subdomain on prod)
  base_url: https://www.data.gouv.fr
  # oauth settings
  # FIXME:
  oauth_client_id: 66e30254d3cc5d5b52a4b6ec

robots:
  disallow:
  sitemap:
  meta: 'noindex, nofollow'

# UI customizations
website:
  title: 'accessibilite.data.gouv.fr'
  formatted_title: '<i>accessibilite.</i><b>data.gouv</b><i>.fr</i>'
  rf_title: 'RÉPUBLIQUE<br>FRANÇAISE'
  service_logo: '/logos/accessibilite-logo.svg'
  badge:
    display: true
    text: 'BETA'
    style: 'blue-cumulus'
  # leave empty if not pertinent
  logo_operator:
  homepage:
    title: "Les données ouvertes relatives à l'accessibilité"
    subtitle: "accessibilite.data.gouv.fr centralise et structure les données publiques relatives à l'accessibilité. Vous y trouverez des données brutes téléchargeables et utilisables de manière libre et gratuite."
    sections:
      - title: Des bouquets de données pour articuler politiques publiques et données territoriales
        content: "Créez un bouquet pour inventorier les données utiles à un cas d'usage : une politique publique sur un territoire"
        sub_section_datasets:
        sub_section_cards:
          title:
          cards:
            - name: 'Accessibilité numérique'
              description: "Données sur l'immobilier dédié aux activités de logistique (bâti, entrepôts, stockage, etc.)."
              url: 'bouquets?theme=accessibilite-numerique'
              image_url: '/logistique/assets/immobilier.jpg'
            - name: 'Accessibilité PMR'
              description: "Données sur l'infrastructure des activités de logistique (réseaux, voirie, zones livraison, etc.)."
              url: 'bouquets?theme=accessibilite-accessibilite-pmr'
              image_url: '/logistique/assets/infra.jpg'
        sub_section_tiles:
        sub_section_buttons:
    meta_description: accessibilite.data.gouv.fr référence et centralise les données relatives à l'accesssibilité.
  header_button:
    display: false
    label: 'Donnez votre avis'
    link:
  header_search:
    display: true
    placeholder: Rechercher...
  search_bar:
    display: true
    placeholder: Rechercher une donnée
  secondary_search:
    display: false
    name:
    link:
  footer_phrase: "Ce site est une déclinaison thématique de data.gouv.fr sur les données relatives à l'accessibilité."
  footer_external_links:
    - label: 'data.gouv.fr'
      href: 'https://www.data.gouv.fr'
      title: 'data.gouv.fr - nouvelle fenêtre'
    - label: 'legifrance.gouv.fr'
      href: 'https://www.legifrance.gouv.fr/'
      title: 'legifrance - nouvelle fenêtre'
    - label: 'gouvernement.fr'
      href: 'https://www.gouvernement.fr'
      title: 'gouvernement.fr - nouvelle fenêtre'
  footer_mandatory_links:
    - label: 'Contact'
      href: 'https://tally.so/r/m61AqO'
    - label: 'Plan du site'
      to: '/sitemap'
    - label: "Conditions générales d'utilisation"
      to: '/terms'
    - label: 'Politique de confidentialité'
      href: 'https://www.data.gouv.fr/fr/suivi/'
    - label: 'Accessibilité : partiellement conforme'
      to: '/accessibility'
  notice:
    display: true
    content: ⚠️ Vous naviguez sur une version de développement d'accessibilite.data.gouv.fr ⚠️
    closeable: false
  menu:
    - text: Accueil
      to: /
    - text: Données
      to: /datasets
    - text: Bouquets
      to: /bouquets
    - text: À propos
      to: /about
  router:
    disable:
      - topics
    static_pages:
      - title: 'À propos'
        id: 'about'
        route: '/about'
        url: '/ecospheres/pages/about.md'
      - title: 'Accessibilité'
        id: 'accessibility'
        route: '/accessibility'
        url: '/ecospheres/pages/accessibility.md'
      - title: "Conditions générales d'utilisation"
        id: 'terms'
        route: '/terms'
        url: '/ecospheres/pages/terms.md'
  show_quality_component: true
  oauth_option: true
  # debounce high enough for accessibility (screen readers will announce results)
  default_debounce_wait: 600
  pagination_sizes:
    organizations_list: 9
    topics_list: 20
    files_list: 6
  contact_email: ecospheres@developpement-durable.gouv.fr
  home_banner_colors:
    - '#D6E3A1'
    - '#BFDCB7'
    - '#A7D4CD'
  matomo:
    host: 'https://stats.data.gouv.fr'
    siteId:
  datasets:
    # TODO: better place for that?
    add_to_topic:
      enable: true
      page: bouquets
      dataset_editorialization: true
    # similar to QUALITY_METADATA_BACKEND_IGNORE on data.gouv.fr
    harvest_backends_quality_warning:
      - CSW-ISO-19139
    show_extended_information_panel: true
  # TODO: better place for that?
  topics:
    can_add_topics:
      everyone: true
      authorized_users:
  sitemap:
    - name: Accueil
      path: /
    - name: Bouquets
      path: /bouquets
    - name: Jeux de données
      path: /datasets
    - name: Organisations
      path: /organizations
    - name: À propos
      path: /about
    - name: Conditions générales d’utilisation
      path: /terms
    - name: Accessibilité
      path: /accessibility

organizations:

# shared themes list for indicators and bouquets
definitions: &definitions
  themes_list: &themes_list
    - id: accessibilite-pmr
      name: Personnes à Mobilité Réduite
    - id: accessibilite-numerique
      name: Personnes à Mobilité Réduite
    - id: autre
      name: Autre

# Configuration format for pages:
pages:
  # DATASETS
  datasets:
    list_all: true
    universe_query:
      topic: 682b1be88b2474e04b3cb19a
    tag_prefix:
    title: Jeux de données
    breadcrumb_title: Données
    labels:
      singular: jeu de données
      plural: jeux de données
      extended: jeu de données
    search:
      input: Rechercher un jeu de données
    banner:
    discussions:
      display: true
      create: true
    filters: []
  # BOUQUETS
  bouquets:
    list_all: true
    universe_query:
      tag: accessibilite-datagouvfr
    tag_prefix: accessibilite-datagouvfr
    title: Bouquets
    breadcrumb_title:
    labels:
      singular: bouquet
      plural: bouquets
      extended: bouquet de données
    search:
      input: Filtrer les bouquets
    banner:
    discussions:
      display: true
      create: true
    filters:
      - name: Afficher les brouillons
        id: include_private
        type: checkbox
        default_option:
        default_value: true
        authenticated: true
        values: []
      - name: Thématique
        default_option: Toutes les thématiques
        id: theme
        type: select
        color: green-emeraude
        use_tag_prefix: true
        # TODO: use a dedicated config for the form?
        form:
          required: true
        values: *themes_list
      - name: Couverture territoriale
        default_option:
        id: geozone
        type: spatial_zone
