datagouvfr:
  # data.gouv.fr base URL
  base_url: https://demo.data.gouv.fr
  # oauth settings
  oauth_client_id:
  # pkce client secret, explicitely public
  oauth_client_secret:

universe:
  # "universe" topic id
  topic_id: 65d47fd070159853a2f399bb # meteo-test
  # universe name, used as bouquets tag
  name: dlnuf

# UI customizations
website:
  title: 'dlnuf.data.gouv.fr'
  rf_title: 'RÉPUBLIQUE<br>
    FRANÇAISE'
  service_logo: '/logos/dlnuf.svg'
  badge:
    display: true
    text: 'BETA'
    style: 'blue-cumulus'
  # leave empty if not pertinent

  homepage:
    title: 'Acteurs publics, utilisez la donnée pour simplifier vos services 🧘 !'
    subtitle: 'Simpligiez les démarches et services des citoyens, entreprises et associations en récupérant pour eux leurs informations administratives grâces aux API et aux données ! Vous gagnerez aussi du temps !' 
    below_hero: >-
      ## Améliorer les services à destination :

      ### 👱 des particuliers
      
      Simplifiez les démarches des citoyens et facilitez l'instruction de leurs dossiers :
      <br/>
      [4 tuiles avec les 4 principales démarches]
      <br/>
      [Boutons Toutes les démarches des particuliers]

      ### 💼 des entreprises

      Simplifiez les démarches des entreprises et facilitez l'instruction de leurs dossiers :
      <br/>
      [4 tuiles avec les 4 principales démarches]
      <br/>
      [Boutons Toutes les démarches des entreprises]

      ### 🎭 des associations

      Simplifiez les démarches des associations et facilitez l'instruction de leurs dossiers :
      <br/>
      [4 tuiles avec les 4 principales démarches]
      <br/>
      [Boutons Toutes les démarches des associations]
    below_topics: >-
      ## Comment et pourquoi simplifier vos démarches ?
      
      Administrations et collectivités, en intégrant des API ou des données dans vos démarches et/ou votre système d’information :


      - 🗄 **Vous accédez facilement aux données administratives de vos usagers**, qu'elles soient publiques ou protégées et provenant de [nombreux fournisseurs](/organizations) ;


      - ⏰ **Vous accélérez le traitement des démarches car vos agents instructeurs** n’ont pas de vérifications supplémentaires à réaliser, les informations obtenues que nous vous recommandons sont certifiées 🔎 ;


      - 🎢 **Vous augmentez le pourcentage des démarches finalisées** car vous faîtes gagner du temps à l’usager ;


      - 🎯 **Vous participez activement à la simplification des démarches en mettant en place le « _[Dites-le-nous une fois](/dlnuf)_ »** : vous ne demandez plus à vos usagers une information qu’ils ont déjà donnée ou que l’administration connaît déjà. Vous vous mettez ainsi en conformité avec la législation et, plus particulièrement l’[Article L113-12 du Code des relations entre le public et l’administration](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000037313155).


      - 💌 **Vous réduisez le taux de non recours**, plus particulièrement si vous mettez en place des démarches proactives. [En savoir plus sur la proactivité](/proactivite).

      
      Pour en savoir plus, consultez nos [guides de la simplification](/guides).

  header_button:
    display: true
    label: 'Compte Datapass'
    link: https://datapass.api.gouv.fr/
  search_bar:
    display: false
    placeholder: 'Rechercher un jeu de données'
  secondary_search:
    display: false
    name: 'Recherche guidée'
    link: '/form'
  router_items:
    - name: 'Accueil'
      id: 'home'
      linkPage: '/'
      type: 'component'
      display_menu: false
    - name: 'Cas d’usages'
      id: 'topics'
      linkPage: '/topics'
      type: 'component'
      display_menu: true
    - name: 'Guides de la simplification'
      id: 'guides'
      linkPage: '/guides'
      type: 'page'
      url: '/dlnuf/pages/guides.md'
      display_menu: true
    - name: 'Toutes les API & données utiles'
      id: 'datasets'
      linkPage: '/datasets'
      type: 'component'
      display_menu: true
    - name: 'Accessibilité'
      id: 'accessibility'
      linkPage: '/accessibility'
      type: 'page'
      display_menu: false
      url: '/dlnuf/pages/accessibility.md'
    - name: 'Organisations'
      id: 'organizations'
      linkPage: '/organizations'
      type: 'component'
      display_menu: false
  # img should be square
  home_buttons:
    - name: toto
      link: https://toto.com
      title: tutu
      img: https://www.gitbook.com/cdn-cgi/image/width=256,dpr=2,height=40,fit=contain,format=auto/https%3A%2F%2F3786092575-files.gitbook.io%2F~%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252FnSrS1oz2N9yTlykjBxxZ%252Flogo%252F6aYHAmnUeCAW5cCPwnIy%252FLIGHT.png%3Falt%3Dmedia%26token%3D7ad63c1f-8c63-4ea0-bd5d-5655c9b7192b
    - name: toto
      link: https://toto.com
      title: test
      img: https://www.gitbook.com/cdn-cgi/image/width=256,dpr=2,height=40,fit=contain,format=auto/https%3A%2F%2F3786092575-files.gitbook.io%2F~%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252FnSrS1oz2N9yTlykjBxxZ%252Flogo%252F6aYHAmnUeCAW5cCPwnIy%252FLIGHT.png%3Falt%3Dmedia%26token%3D7ad63c1f-8c63-4ea0-bd5d-5655c9b7192b
  show_topic_charts: true
  show_quality_component: true
  show_dataset_metadata_panel: false
  list_highlighted_topics:
    - id: '65d48848825a9cf9fc3d8f3a'
      name: 'Marchés publics'
  url_highlighted_topics: 'topics'
  type_highlighted_topics: 'card' #card or tile
  oauth_option: false
  footer_phrase: 'Ce site permet aux administrations et collectivités territoriales de connaître les API et les données qui leur permettent de simplifier leurs démarches pour les particuliers, les entreprises et les associations.'
  footer_external_links:
    - label: 'API Entreprise'
      href: 'https://www.entreprise.api.gouv.fr'
    - label: 'API Particulier'
      href: 'https://www.particulier.api.gouv.fr'
    - label: 'data.gouv.fr'
      href: 'https://www.data.gouv.fr'
  footer_mandatory_links:
    - label: 'Licences'
      href: 'https://www.data.gouv.fr/fr/pages/legal/licences/'
    - label: "Conditions générales d'utilisation"
      href: 'https://www.data.gouv.fr/fr/terms/'
    - label: 'Politique de confidentialité'
      href: 'https://www.data.gouv.fr/fr/suivi/'
    - label: 'Accessibilité : non conforme'
      to: '/accessibility'
  logo_operator: ''
  # display settings
  pagination_sizes:
    organizations_list: 9
    topics_list: 100
    files_list: 6
  home_banner_colors:
    - '#D6DAF7'
    - '#DBA8A8'
    - '#1258EB'
  env: 'prod'
  matomo:
    host: 'https://stats.data.gouv.fr'
    siteId: 292
  discussions:
    dataset:
      display: true
      create: false
    topic:
      display: false
      create: false
organizations:
  # list of organisations' ids that should be handled by the portal
  # to find an id go to https://www.data.gouv.fr/fr/organizations/ministere-de-la-transition-ecologique/
  # then Informations > ID at the bottom of the page
  # Dinum
  - 57fe2a35c751df21e179df72
  # Insee
  - 534fff81a3a7292c64a77e5c
  
