# config file for meteo-france

site_id: meteodatagouvfr

datagouvfr:
  # data.gouv.fr base URL
  base_url: https://www.data.gouv.fr
  # oauth settings
  oauth_client_id: 5e6f426e634f417810ab794b

robots:
  disallow:
  sitemap:
  meta: 'noindex, nofollow'

# UI customizations
website:
  title: 'meteo.data.gouv.fr'
  formatted_title: '<i>meteo.</i><b>data.gouv</b><i>.fr</i>'
  rf_title: 'RÉPUBLIQUE<br>
    FRANÇAISE'
  service_logo: '/logos/meteo-france-logo.svg'
  badge:
    display: false
    text: 'BETA'
    style: 'blue-cumulus'
  # leave empty if not pertinent
  homepage:
    title: 'La météo et le climat en Open Data'
    subtitle: 'meteo.data.gouv.fr vise à référencer, héberger et diffuser les données publiques météorologiques produites par Météo-France. Vous y trouverez des données téléchargeables et utilisables de manière libre et gratuite.'
    sections:
      - title: Thématiques
        content:
        sub_section_datasets:
        sub_section_cards:
          class: fr-col-md-6
          cards:
            - name: 'Données climatologiques (par station et spatialisées)'
              description: 'Données climatologiques pour toutes les stations françaises depuis leur ouverture, pour tous les paramètres disponibles.'
              url: 'datasets?category=climatologique-base'
              image_url: '/meteo-france/assets/climatologie.png'
            - name: 'Données de référence pour le changement climatique'
              description: 'Données recommandées par Météo-France pour réaliser des diagnostics et études climatiques.'
              url: 'datasets?category=climatologique-changement-climatique'
              image_url: '/meteo-france/assets/climatique.jpg'
            - name: 'Données de Prévision Numérique du Temps (PNT)'
              description: 'Données temps réel des dernières prévisions des modèles de prévision numérique jusqu’à 4 jours d’échéances.'
              url: 'datasets?category=pnt'
              image_url: '/meteo-france/assets/pnt.png'
            - name: 'Informations sur les stations'
              description: 'Accès aux caractéristiques des stations météorologiques de métropole et d’outre-mer en service.'
              url: 'datasets?category=stations'
              image_url: '/meteo-france/assets/station.png'
            - name: 'Fiches climatologiques'
              description: "Fiches synthétiques contenant les moyennes mensuelles, les normales et les records d'une station."
              url: 'datasets?category=fiches'
              image_url: '/meteo-france/assets/fiche.png'
        sub_section_tiles:
          title:
          tiles:
        sub_section_buttons:
      - title: Actualités
        content: >-
          Retours sur le hackathon du 8 et 9 avril dernier 🚀


          [En savoir plus](/hackathon)
        sub_section_datasets:
        sub_section_cards:
        sub_section_tiles:
        sub_section_buttons:
    meta_description:
  header_button:
    display: true
    label: 'Donnez votre avis'
    link: https://tally.so/r/wQ7y47
  header_search:
    display: true
    placeholder: Rechercher...
  search_bar:
    display: true
    placeholder: 'Rechercher un jeu de données'
  secondary_search:
    display: true
    name: 'Recherche guidée'
    link: '/form'
  menu:
    - text: Données
      to: /datasets
    - text: Recherche guidée
      to: /form
    - text: 'Hackathon le 8 et 9 avril 🚀'
      to: /hackathon
    - text: A propos
      to: /about
  router:
    disable:
      - organizations_routes
      - topic_routes
    static_pages:
      - title: 'A propos'
        id: 'about'
        route: '/about'
        url: '/meteo-france/pages/about.md'
      - title: 'Accessibilité'
        id: 'accessibility'
        route: '/accessibility'
        url: '/meteo-france/pages/accessibility.md'
      - title: 'Hackathon le 8 et 9 avril 🚀'
        id: 'hackathon'
        route: '/hackathon'
        url: '/meteo-france/pages/hackathon.md'
  show_quality_component: true
  oauth_option: true
  footer_phrase: 'Ce site est une déclinaison thématique de data.gouv.fr sur les données relatives à la météo et au climat réalisé en collaboration avec Météo-France.'
  footer_external_links:
    - label: 'meteofrance.com'
      href: 'https://meteofrance.com/'
    - label: 'Portail des API Météo-France'
      href: 'https://portail-api.meteofrance.fr/'
    - label: 'data.gouv.fr'
      href: 'https://www.data.gouv.fr'
  footer_mandatory_links:
    - label: 'Licences'
      href: 'https://www.data.gouv.fr/fr/pages/legal/licences/'
    - label: "Conditions générales d'utilisation"
      href: 'https://www.data.gouv.fr/fr/terms/'
    - label: 'Politique de confidentialité'
      href: 'https://www.data.gouv.fr/fr/suivi/'
    - label: 'Accessibilité : non conforme'
      to: '/accessibility'
  logo_operator:
    src: 'https://static.data.gouv.fr/avatars/81/6374003e904fad9ddac7436315fd15-100.png'
    header:
      width: '60px'
      height: '60px'
    footer:
      width: '92px'
      height: '92px'
  notice:
    display: false
    content: Notice avec un [lien beta](/beta) et du _style_
    closeable: false
  # debounce high enough for accessibility (screen readers will announce results)
  default_debounce_wait: 600
  # display settings
  pagination_sizes:
    organizations_list: 9
    topics_list: 20
    files_list: 6
  home_banner_colors:
    - '#F7EED4'
    - '#ECEEE6'
    - '#E2EEF8'
  env: 'prod'
  matomo:
    host: 'https://stats.data.gouv.fr'
    siteId: 292
  datasets:
    add_to_topic:
    # similar to QUALITY_METADATA_BACKEND_IGNORE on data.gouv.fr
    harvest_backends_quality_warning: []
    show_extended_information_panel: false
  topics:
    can_add_topics:
      everyone: false
      authorized_users:

# list of organisations' ids that should be handled by the portal
# to find an id go to https://www.data.gouv.fr/fr/organizations/ministere-de-la-transition-ecologique/
# then Informations > ID at the bottom of the page
organizations:

# cf configs/ecospheres/config.yaml for pages config format details
pages:
  datasets:
    list_all: true
    tag_prefix:
    universe_query:
      tag: meteodatagouvfr
    title: Jeux de données
    breadcrumb_title: Données
    labels:
      singular: jeu de données
      plural: jeux de données
      extended: jeu de données
    search:
      input: Rechercher un jeu de données
    banner:
    discussions:
      display: true
      create: false
    filters:
      - name: Catégories
        default_option: Toutes les catégories
        id: category
        type: select
        child: subcategory
        color: noop
        use_tag_prefix: false
        values:
          - id: climatologique-base
            name: Données climatologiques de base
          - id: climatologique-changement-climatique
            name: Données climatologiques de référence pour le changement climatique
          - id: pnt
            name: Données de Prévision Numérique du Temps (PNT)
          - id: stations
            name: Informations sur les stations
      - name: Sous-catégories
        default_option: Toutes les sous-catégories
        id: subcategory
        type: select
        color: noop
        use_tag_prefix: false
        values:
          # parent-category: stations
          - name: Stations du réseau Météo-France
            id: stations-mf
            parent: stations
          - name: Stations complémentaires
            id: stations-complementaires
            parent: stations
          - name: Fiches de poste (par département)
            id: fiches-postes-dep
            parent: stations
          - name: Fiches de postes réseau complémentaire (par département)
            id: fiches-postes-complementaire-dep
            parent: stations
          - name: Informations réseau
            id: infos-reseau
            parent: stations
          # parent-category: climatologique-base
          - name: Données à la station du réseau Météo-France
            id: climatologique-base-donnees-stations-mf
            parent: climatologique-base
          - name: Données stations complémentaires
            id: climatologique-base-donnees-stations-complementaires
            parent: climatologique-base
          - name: Données spatialisées
            id: climatologique-base-donnees-spatialisees
            parent: climatologique-base
          - name: Données à la station
            id: climatologique-changement-climatique-donnees-station
            parent: climatologique-changement-climatique
          - name: Données spatialisées
            id: climatologique-changement-climatique-donnees-spatialisees
            parent: climatologique-changement-climatique
          # parent-category: pnt
          - name: Modèle ARPEGE
            id: pnt-arpege
            parent: pnt
          - name: Modèle AROME Métropole
            id: pnt-arome-metropole
            parent: pnt
          - name: Modèle AROME Outre-Mer
            id: pnt-arome-outre-mer
            parent: pnt
          - name: Modèle de vagues et surcote
            id: pnt-vague-surcote
            parent: pnt
