# config file for meteo-france

datagouvfr:
  # data.gouv.fr base URL
  base_url: https://www.data.gouv.fr
  # oauth settings
  oauth_client_id:

universe:
  # "universe" topic id
  topic_id: 6571f222129681e83de11aa2 # meteo-test
  # universe name, used as bouquets tag
  name: meteo-france

robots:
  disallow:
  sitemap:
  meta: 'noindex, nofollow'

# UI customizations
website:
  title: 'meteo.data.gouv.fr'
  formatted_title: '<i>meteo.</i><b>data.gouv</b><i>.fr</i>'
  rf_title: 'RÉPUBLIQUE<br>
    FRANÇAISE'
  service_logo: '/logos/meteo-france-logo.svg'
  badge:
    display: false
    text: 'BETA'
    style: 'blue-cumulus'
  # leave empty if not pertinent
  homepage:
    title: 'La météo et le climat en Open Data'
    subtitle: 'meteo.data.gouv.fr vise à référencer, héberger et diffuser les données publiques météorologiques produites par Météo-France. Vous y trouverez des données téléchargeables et utilisables de manière libre et gratuite.'
    sections:
      - title: Thématiques
        content:
        sub_section_datasets:
        sub_section_cards:
        sub_section_tiles:
          title:
          tiles:
            - id: '6571f26dc009674feb726be9'
              name: 'Données climatologiques de base'
              description: 'Données climatologiques pour toutes les stations françaises depuis leur ouverture, pour tous les paramètres disponibles.'
              url: 'datasets?topic=6571f26dc009674feb726be9'
            - id: '6571f2db0273fc306408f265'
              name: 'Données climatologiques de référence pour le changement climatique'
              description: 'Données recommandées par Météo-France pour réaliser des diagnostics et études climatiques.'
              url: 'datasets?topic=6571f2db0273fc306408f265'
            - id: '65e0c82c2da27c1dff5fa66f'
              name: 'Données de Prévision Numérique du Temps (PNT)'
              description: 'Accès en temps réel aux résultats des dernières prévisions des modèles de prévision numérique jusqu’à 4 jours d’échéance.'
              url: 'datasets?topic=65e0c82c2da27c1dff5fa66f'
        sub_section_buttons:
      - title: Actualités
        content: >-
          Retours sur le hackathon du 8 et 9 avril dernier 🚀


          [En savoir plus](/hackathon)
        sub_section_datasets:
        sub_section_cards:
        sub_section_tiles:
        sub_section_buttons:
    meta_description:
  header_button:
    display: true
    label: 'Donnez votre avis'
    link: https://tally.so/r/wQ7y47
  header_search:
    display: true
    placeholder: Rechercher...
  search_bar:
    display: true
    placeholder: 'Rechercher un jeu de données'
  secondary_search:
    display: true
    name: 'Recherche guidée'
    link: '/form'
  menu:
    - text: Données
      to: /datasets
    - text: Bouquets
      to: /bouquets
    - text: Recherche guidée
      to: /form
    - text: 'Hackathon le 8 et 9 avril 🚀'
      to: /hackathon
    - text: A propos
      to: /about
  router:
    disable:
      - organizations_routes
      - topics
    pages:
      - title: 'A propos'
        id: 'about'
        route: '/about'
        url: '/meteo-france/pages/about.md'
      - title: 'Accessibilité'
        id: 'accessibility'
        route: '/accessibility'
        url: '/meteo-france/pages/accessibility.md'
      - title: 'Hackathon le 8 et 9 avril 🚀'
        id: 'hackathon'
        route: '/hackathon'
        url: '/meteo-france/pages/hackathon.md'
  show_quality_component: true
  list_search_topics:
    - id: '6571f26dc009674feb726be9'
      name: 'Données climatologiques de base'
    - id: '6571f2db0273fc306408f265'
      name: 'Données climatologiques de référence pour le changement climatique'
    - id: '65e0c82c2da27c1dff5fa66f'
      name: 'Données de Prévision Numérique du Temps (PNT)'
  url_search_topics: 'datasets'
  oauth_option: true
  footer_phrase: 'Ce site est une déclinaison thématique de data.gouv.fr sur les données relatives à la météo et au climat réalisé en collaboration avec Météo-France.'
  footer_external_links:
    - label: 'meteofrance.com'
      href: 'https://meteofrance.com/'
    - label: 'Portail des API Météo-France'
      href: 'https://portail-api.meteofrance.fr/'
    - label: 'data.gouv.fr'
      href: 'https://www.data.gouv.fr'
  footer_mandatory_links:
    - label: 'Licences'
      href: 'https://www.data.gouv.fr/fr/pages/legal/licences/'
    - label: "Conditions générales d'utilisation"
      href: 'https://www.data.gouv.fr/fr/terms/'
    - label: 'Politique de confidentialité'
      href: 'https://www.data.gouv.fr/fr/suivi/'
    - label: 'Accessibilité : non conforme'
      to: '/accessibility'
  logo_operator:
    src: 'https://static.data.gouv.fr/avatars/81/6374003e904fad9ddac7436315fd15-100.png'
    header:
      width: '60px'
      height: '60px'
    footer:
      width: '92px'
      height: '92px'
  notice:
    display: false
    content: Notice avec un [lien beta](/beta) et du _style_
    closeable: false
  # debounce high enough for accessibility (screen readers will announce results)
  default_debounce_wait: 600
  # display settings
  pagination_sizes:
    organizations_list: 9
    topics_list: 20
    files_list: 6
  home_banner_colors:
    - '#F7EED4'
    - '#ECEEE6'
    - '#E2EEF8'
  env: 'prod'
  matomo:
    host: 'https://stats.data.gouv.fr'
    siteId: 292
  discussions:
    dataset:
      display: true
      create: false
    topic:
      display: false
      create: false
  datasets:
    organization_filter: false
    add_to_bouquet: true
    # similar to QUALITY_METADATA_BACKEND_IGNORE on data.gouv.fr
    harvest_backends_quality_warning: []
    show_extended_information_panel: false
  topics:
    slug: bouquets
    name: bouquet
    extras_key: 'meteofrance'
    themes:
      usage: false
      main_name: thématique
      secondary_name: chantier
    # include a list page with all topics
    list_all: false
    display_metadata: false
    activate_read_more: false
    dataset_editorialization: false
    can_add_topics:
      everyone: false
      authorized_users:
        - 6230733357772160a4f77fbaxx
themes:
  - name: Données climatologiques
    color: 043574
    textColor: FFFFFF
    subthemes:
      - name: Informations sur les stations
      - name: Données climatologiques de base
      - name: Références à la station
      - name: Données de références pour le changement climatiques
  - name: Données de prévision numérique du temps (PNT)
    color: 1E929E
    textColor: FFFFFF
    subthemes:
      - name: ARPEGE
      - name: AROME
      - name: Modèle de vague haute

# list of organisations' ids that should be handled by the portal
# to find an id go to https://www.data.gouv.fr/fr/organizations/ministere-de-la-transition-ecologique/
# then Informations > ID at the bottom of the page
organizations:
