services:
  data-gouv-front:
    image: node:21
    container_name: ddev-${DDEV_SITENAME}-data-gouv-front
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html:cached
    ports:
      - '5173:5173'
    command: sleep infinity
