# inspired from https://github.com/dokku/github-action/blob/master/example-workflows/review-app.yaml

name: Deploy review app

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:
    inputs:
      site:
        description: 'Site to deploy (ecospheres, meteo-france, or logistique)'
        required: true
        default: 'ecospheres'
        type: choice
        options:
          - ecospheres
          - meteo-france
          - logistique
      pr_number:
        description: 'PR number (required for manual deployments)'
        required: true
        type: string

jobs:
  handle_review_app:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.site || 'ecospheres' }}
      cancel-in-progress: false
    permissions:
      deployments: write
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) ||
      github.event_name == 'workflow_dispatch'
    steps:
      - name: Set environment variables
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "SITE_ID=${{ github.event.pull_request.head.ref == 'main' && 'ecospheres' || 'ecospheres' }}" >> $GITHUB_ENV
            echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            echo "SITE_ID=${{ inputs.site }}" >> $GITHUB_ENV
            echo "PR_NUMBER=${{ inputs.pr_number }}" >> $GITHUB_ENV
          fi

      - name: Debug event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Pull request state: ${{ github.event.pull_request.state || 'N/A' }}"
          echo "Site ID: ${{ env.SITE_ID }}"
          echo "PR number: ${{ env.PR_NUMBER }}"

      - name: Cloning repo
        if: github.event_name == 'workflow_dispatch' || github.event.action != 'closed'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start deployment
        if: github.event_name == 'workflow_dispatch' || github.event.action != 'closed'
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: ${{ github.token }}
          environment: ${{ env.SITE_ID }}-preview
          initial-status: in_progress
          transient-environment: true

      - name: Create the review app
        if: github.event_name == 'workflow_dispatch' || github.event.action == 'opened' || github.event.action == 'reopened'
        uses: dokku/github-action@master
        # ignore errors as the app might already exist on workflow_dispatch
        continue-on-error: true
        with:
          command: review-apps:create
          git_remote_url: ${{ secrets.REVIEW_APP_SSH_URL }}
          review_app_name: deploy-preview-${{ env.PR_NUMBER }}--${{ env.SITE_ID }}
          ssh_private_key: ${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}

      - name: Set site id as build arg
        if: always()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REVIEW_APP_SSH_HOST }}
          username: dokku
          key: ${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker-options:add deploy-preview-${{ env.PR_NUMBER }}--${{ env.SITE_ID }} build "--build-arg VITE_SITE_ID=${{ env.SITE_ID }}"

      - name: Push to dokku
        if: github.event_name == 'workflow_dispatch' || github.event.action != 'closed'
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.REVIEW_APP_SSH_URL }}
          review_app_name: deploy-preview-${{ env.PR_NUMBER }}--${{ env.SITE_ID }}
          ssh_private_key: ${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}
          git_push_flags: '--force'
          branch: 'main'

      - name: Enable SSL with Let's Encrypt
        if: github.event_name == 'workflow_dispatch' || github.event.action == 'opened' || github.event.action == 'reopened'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REVIEW_APP_SSH_HOST }}
          username: dokku
          key: ${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            letsencrypt:enable deploy-preview-${{ env.PR_NUMBER }}--${{ env.SITE_ID }}

      - uses: mikefarah/yq@de2f77b49cbd40fd67031ee602245d0acc4ac482
        id: get-sites
        with:
          cmd: yq '.on.workflow_dispatch.inputs.site.options[]' '.github/workflows/review-app.yml'

      - name: Destroy all review apps
        if: github.event.action == 'closed'
        run: |
          echo "${{ steps.get-sites.outputs.result }}" | while read site; do
            echo "Destroying review app for site: $site"
            ssh -i <(echo "${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}") \
                -o StrictHostKeyChecking=no \
                dokku@${{ secrets.REVIEW_APP_SSH_HOST }} \
                apps:destroy deploy-preview-${{ env.PR_NUMBER }}--$site || true
          done

      - name: Update deployment status
        if: github.event_name == 'workflow_dispatch' || github.event.action != 'closed'
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: https://deploy-preview-${{ env.PR_NUMBER }}--${{ env.SITE_ID }}.sandbox.data.developpement-durable.gouv.fr
          state: ${{ job.status == 'success' && 'success' || 'failure' }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
