# inspired from https://github.com/dokku/github-action/blob/master/example-workflows/review-app.yaml

name: Deploy review app

on: pull_request

jobs:
  create_review_app:
    runs-on: ubuntu-latest
    # only run when a pull request is opened
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and push the review app
        uses: dokku/github-action@master
        with:
          # create a review app
          command: review-apps:create
          git_remote_url: ${{ secrets.REVIEW_APP_SSH_URL }}
          # specify a name for the review app
          # TODO: handle multiple review apps for the same PR (e.g. deploy-preview-123--meteo-france)
          review_app_name: deploy-preview-${{ github.event.pull_request.number }}--ecospheres
          ssh_private_key: ${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}

  deploy_review_app:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    # only run when a pull request is not opened or closed
    if: github.event_name == 'pull_request' && github.event.action != 'opened' && github.event.action != 'closed'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: ${{ github.token }}
          environment: preview
          initial-status: in_progress
          ref: ${{ github.event.pull_request.head.sha }}
          transient-environment: true

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          # create a review app
          git_remote_url: ${{ secrets.REVIEW_APP_SSH_URL }}
          # specify a name for the review app
          review_app_name: deploy-preview-${{ github.event.pull_request.number }}--ecospheres
          ssh_private_key: ${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}
          git_push_flags: '--force'

      - name: Update deployment status
        if: always()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: https://deploy-preview-${{ github.event.pull_request.number }}--ecospheres.sandbox.data.developpement-durable.gouv.fr
          state: ${{ job.status == 'success' && 'success' || 'failure' }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

  destroy_review_app:
    runs-on: ubuntu-latest
    # only run when a pull request is closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Destroy the review app
        uses: dokku/github-action@master
        with:
          # destroy a review app
          command: review-apps:destroy
          git_remote_url: ${{ secrets.REVIEW_APP_SSH_URL }}
          # specify a name for the review app
          review_app_name: deploy-preview-${{ github.event.pull_request.number }}--ecospheres
          ssh_private_key: ${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}
