# inspired from https://github.com/dokku/github-action/blob/master/example-workflows/review-app.yaml

name: Deploy review app

on: pull_request

jobs:
  handle_review_app:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start deployment
        if: always()
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: ${{ github.token }}
          environment: ecospheres-preview
          initial-status: in_progress
          transient-environment: true

      - name: Create and push the review app
        if: github.event.action == 'opened'
        uses: dokku/github-action@master
        with:
          command: review-apps:create
          git_remote_url: ${{ secrets.REVIEW_APP_SSH_URL }}
          review_app_name: deploy-preview-${{ github.event.pull_request.number }}--ecospheres
          ssh_private_key: ${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}
          branch: 'main'

      - name: Push to dokku
        if: github.event.action != 'opened' && github.event.action != 'closed'
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.REVIEW_APP_SSH_URL }}
          review_app_name: deploy-preview-${{ github.event.pull_request.number }}--ecospheres
          ssh_private_key: ${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}
          git_push_flags: '--force'

      - name: Enable SSL with Let's Encrypt
        if: github.event.action == 'opened'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REVIEW_APP_SSH_HOST }}
          username: dokku
          key: ${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            letsencrypt:enable deploy-preview-${{ github.event.pull_request.number }}--ecospheres

      - name: Destroy the review app
        if: github.event.action == 'closed'
        uses: dokku/github-action@master
        with:
          command: review-apps:destroy
          git_remote_url: ${{ secrets.REVIEW_APP_SSH_URL }}
          review_app_name: deploy-preview-${{ github.event.pull_request.number }}--ecospheres
          ssh_private_key: ${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}

      - name: Update deployment status
        if: github.event.action != 'closed'
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: https://deploy-preview-${{ github.event.pull_request.number }}--ecospheres.sandbox.data.developpement-durable.gouv.fr
          state: ${{ job.status == 'success' && 'success' || 'failure' }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (destroy)
        if: github.event.action == 'closed'
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          state: ${{ job.status == 'success' && 'inactive' || 'failure' }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
