# inspired from https://github.com/dokku/github-action/blob/master/example-workflows/review-app.yaml

name: Deploy review app

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  handle_review_app:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.site }}
      cancel-in-progress: true
    strategy:
      matrix:
        site:
          - ecospheres
          - meteo-france
          - logistique
    permissions:
      deployments: write
    # only run if the PR is from the same repo
    if: github.event.pull_request.head.repo.full_name == github.repository && github.event_name == 'pull_request'
    steps:
      - name: Cloning repo
        if: github.event.action != 'closed'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start deployment
        if: github.event.action != 'closed'
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: ${{ github.token }}
          environment: ${{ matrix.site }}-preview
          initial-status: in_progress
          transient-environment: true

      - name: Create the review app
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        uses: dokku/github-action@master
        with:
          command: review-apps:create
          git_remote_url: ${{ secrets.REVIEW_APP_SSH_URL }}
          review_app_name: deploy-preview-${{ github.event.pull_request.number }}--${{ matrix.site }}
          ssh_private_key: ${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}
          # omitting this will prevent the app from being built (which is what we want)
          # branch: 'main'

      - name: Set site id as build arg
        if: always()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REVIEW_APP_SSH_HOST }}
          username: dokku
          key: ${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker-options:add deploy-preview-${{ github.event.pull_request.number }}--${{ matrix.site }} build "--build-arg VITE_SITE_ID=${{ matrix.site }}"

      - name: Push to dokku
        if: github.event.action != 'closed'
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.REVIEW_APP_SSH_URL }}
          review_app_name: deploy-preview-${{ github.event.pull_request.number }}--${{ matrix.site }}
          ssh_private_key: ${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}
          git_push_flags: '--force'
          branch: 'main'

      - name: Enable SSL with Let's Encrypt
        if: github.event.action == 'opened' || github.event.action == 'reopened'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REVIEW_APP_SSH_HOST }}
          username: dokku
          key: ${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            letsencrypt:enable deploy-preview-${{ github.event.pull_request.number }}--${{ matrix.site }}

      - name: Destroy the review app
        if: github.event.action == 'closed'
        uses: dokku/github-action@master
        with:
          command: review-apps:destroy
          git_remote_url: ${{ secrets.REVIEW_APP_SSH_URL }}
          review_app_name: deploy-preview-${{ github.event.pull_request.number }}--${{ matrix.site }}
          ssh_private_key: ${{ secrets.REVIEW_APP_SSH_PRIVATE_KEY }}

      - name: Update deployment status
        if: github.event.action != 'closed'
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment-url: https://deploy-preview-${{ github.event.pull_request.number }}--${{ matrix.site }}.sandbox.data.developpement-durable.gouv.fr
          state: ${{ job.status == 'success' && 'success' || 'failure' }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
